export const TOGGLE_TRIM_DISTRIBUTION = 'TOGGLE_TRIM_DISTRIBUTION';
export const CHANGE_LEFT_SPREAD_DURATION = 'CHANGE_LEFT_SPREAD_DURATION';
export const CHANGE_RIGHT_SPREAD_DURATION = 'CHANGE_RIGHT_SPREAD_DURATION';
